// Mocks generated by Mockito 5.4.4 from annotations
// in final_assignment/test/unit_test/meal_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:final_assignment/core/failure/failure.dart' as _i6;
import 'package:final_assignment/features/meal_plan/domain/entity/meal_entity.dart'
    as _i7;
import 'package:final_assignment/features/meal_plan/domain/repository/meal_repository.dart'
    as _i2;
import 'package:final_assignment/features/meal_plan/domain/usecases/meal_usecase.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeIMealRepository_0 extends _i1.SmartFake
    implements _i2.IMealRepository {
  _FakeIMealRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MealUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockMealUsecase extends _i1.Mock implements _i4.MealUsecase {
  @override
  _i2.IMealRepository get mealRepository => (super.noSuchMethod(
        Invocation.getter(#mealRepository),
        returnValue: _FakeIMealRepository_0(
          this,
          Invocation.getter(#mealRepository),
        ),
        returnValueForMissingStub: _FakeIMealRepository_0(
          this,
          Invocation.getter(#mealRepository),
        ),
      ) as _i2.IMealRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, bool>> addMeal(_i7.MealEntity? meal) =>
      (super.noSuchMethod(
        Invocation.method(
          #addMeal,
          [meal],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, bool>>.value(
            _FakeEither_1<_i6.Failure, bool>(
          this,
          Invocation.method(
            #addMeal,
            [meal],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.Either<_i6.Failure, bool>>.value(
                _FakeEither_1<_i6.Failure, bool>(
          this,
          Invocation.method(
            #addMeal,
            [meal],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, bool>>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i7.MealEntity>>> getAllMeals(
          int? page) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllMeals,
          [page],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, List<_i7.MealEntity>>>.value(
                _FakeEither_1<_i6.Failure, List<_i7.MealEntity>>(
          this,
          Invocation.method(
            #getAllMeals,
            [page],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.Either<_i6.Failure, List<_i7.MealEntity>>>.value(
                _FakeEither_1<_i6.Failure, List<_i7.MealEntity>>(
          this,
          Invocation.method(
            #getAllMeals,
            [page],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, List<_i7.MealEntity>>>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, bool>> deleteMeal(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteMeal,
          [id],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, bool>>.value(
            _FakeEither_1<_i6.Failure, bool>(
          this,
          Invocation.method(
            #deleteMeal,
            [id],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.Either<_i6.Failure, bool>>.value(
                _FakeEither_1<_i6.Failure, bool>(
          this,
          Invocation.method(
            #deleteMeal,
            [id],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, bool>>);
}
